development: &base
  database_url: 'postgres://localhost/formalist_demo_development'
  session_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  assets_server_link_url: "http://localhost:1234"
  assets_server_read_url: "http://localhost:1234"
  attache_host:
  attache_secret_key:
test:
  <<: *base
  database_url: 'postgres://localhost/formalist_demo_test'
production:
  <<: *base
